// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rcpp_BuildTree
List rcpp_BuildTree(NumericVector y, NumericMatrix x, IntegerVector trt, IntegerMatrix ordering, IntegerVector ncat, int ntrt, int min_bucket, int min_split, int max_depth);
RcppExport SEXP abtree_rcpp_BuildTree(SEXP ySEXP, SEXP xSEXP, SEXP trtSEXP, SEXP orderingSEXP, SEXP ncatSEXP, SEXP ntrtSEXP, SEXP min_bucketSEXP, SEXP min_splitSEXP, SEXP max_depthSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type trt(trtSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type ordering(orderingSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ncat(ncatSEXP);
    Rcpp::traits::input_parameter< int >::type ntrt(ntrtSEXP);
    Rcpp::traits::input_parameter< int >::type min_bucket(min_bucketSEXP);
    Rcpp::traits::input_parameter< int >::type min_split(min_splitSEXP);
    Rcpp::traits::input_parameter< int >::type max_depth(max_depthSEXP);
    __result = Rcpp::wrap(rcpp_BuildTree(y, x, trt, ordering, ncat, ntrt, min_bucket, min_split, max_depth));
    return __result;
END_RCPP
}
