# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_BuildTree <- function(y, x, trt, ordering, ncat, ntrt, min_bucket, min_split, max_depth) {
    .Call('abtree_rcpp_BuildTree', PACKAGE = 'abtree', y, x, trt, ordering, ncat, ntrt, min_bucket, min_split, max_depth)
}

